# Install Receptor on CentOS 8
---
- hosts: all
  become: yes
  tasks:
    # Dependencies
    - name: Ensure latest git is installed.
      yum: name=git state=latest
    - name: Ensure latest go is installed.
      yum: name=go state=latest
    - name: Ensure latest python-pip is installed.
      yum: name=python3-pip state=latest
    - name: Ensure latest podman is installed.
      yum: name=podman state=latest
    - name: Ensure latest [pip] pbr is installed.
      pip: name=pbr state=latest

    # Build
    - name: Clone Receptor repo
      git: repo=https://github.com/ansible/receptor.git
           dest=/home/vagrant/receptor
           accept_hostkey=yes
           force=yes
           recursive=no
    - name: Build Receptor
      make:
        chdir: /home/vagrant/receptor